### ISSUE TITLE
Sponsor page does not load for anon Chrome user

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/PeaceGeeks-Website#101]
in Chrome on http://stage.geektheme.peacegeeks.org/sponsor, I see a brief flash of the page, but it doesn't load and remains a blank white page. In IE it loads correctly.

(Submitted by one of our Board members who is a techie)

**Comment by reallyordinary** [comment]
This relates to https://github.com/PeaceGeeksSociety/PeaceGeeks-Website/issues/94 and I need Ben or Mack or somebody with full server access to look at it because it seems to be a problem with the server.

**Comment by reallyordinary** [comment]
Copying in comments from 94 - 

There's something wrong with the Sponsor content type on Stage. Do not know what it is. If you try to view any Sponsor content item directly, you get a white screen. Same if you try to view the Structure content item for Supporters page (which contains views focusing on the Sponsor content type).

Can you get Ben or somebody to have a look at this because I think there's some obscure server issue involved and I don't have sufficient server access to look at logs or other diagnostic materials.

Clarifying - I have zero problems with Sponsor content type on my local dev setup. I can click and view any Sponsor content item. Am not encountering locally the issues occurring on Stage.

**Comment by reallyordinary** [comment]
This was incredibly stupid - problem was being caused by Ad Blocker extension(s). That didn't like the URL being /sponsor. 

Resolved issue by changing URL to /become-sponsor. 

Utterly ridiculous.
