### ISSUE TITLE
Remove "visit website" from the supporter Blacks Family Foundation

### ISSUE THREAD

**Issue by nico-primak** [PeaceGeeksSociety/PeaceGeeks-Website#94]
Blacks Family Foundation do not have a website and currently when you click on the link it opens up the supporters page in a new window. This shouldn't work that way. We need to fix this so that there is no "visit website".

**Comment by PeaceGeeks** [comment]
Don't display 'Visit Website' if no URL included

**Comment by reallyordinary** [comment]
I have this fixed on my local dev but the fix will not show up on stage site. There's something wrong with the Sponsor content type on Stage. Do not know what it is. If you try to view any Sponsor content item directly, you get a white screen. Same if you try to view the Structure content item for Supporters page (which contains views focusing on the Sponsor content type). 

Can you get Ben or somebody to have a look at this because I think there's some obscure server issue involved and I don't have sufficient server access to look at logs or other diagnostic materials.

**Comment by reallyordinary** [comment]
Clarifying - I have zero problems with Sponsor content type on my local dev setup. I can click and view any Sponsor content item. Am not encountering locally the issues occurring on Stage.

**Comment by PeaceGeeks** [comment]
low priority

**Comment by nico-primak** [comment]
High priority since this is the equivalent of a dead link. We can't have those on the site at all, especially on launch.

**Comment by nico-primak** [comment]
I noticed this was done for the "All Sponsors" section but still needs to be done for the "Featured Sponsors".
